// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Internally tagged enum — ts-rs emits a discriminated union with a
 * `kind` tag, matching the rest of the dashboard API style.
 */
export type ActionTarget = { "kind": "Package", ecosystem: string, name: string, version: string, } | { "kind": "Workspace" };
