// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActionDeferRequest = { 
/**
 * Days to defer for. Clamped server-side to `[1, 365]` so a
 * pathological client can't push the dismissal 200 years into
 * the future.
 */
days: bigint | null, reason: string | null, };
