// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionKind } from "./ActionKind";
import type { ActionSeverity } from "./ActionSeverity";
import type { ActionTarget } from "./ActionTarget";

export type Action = { id: string, kind: ActionKind, severity: ActionSeverity, 
/**
 * Canonicalized workspace path — matches the strings used across
 * `/api/workspaces` and `ContaminationChain.workspace` so the
 * dashboard can join freely.
 */
workspace: string, target: ActionTarget, title: string, explanation: string, 
/**
 * When present, the CLI + dashboard show a "Copy fix" button. Exact
 * command depends on the detected package manager (`pm_detect`
 * module); empty for workspace-level actions like RefreshSync.
 */
suggested_command: string | null, 
/**
 * Version the policy would move the dep to, as a raw string. Split
 * out from `suggested_command` so the dashboard can render ranges /
 * badges / diffs without parsing pm-specific command strings
 * (`pnpm add x@^1`, `uv add 'x>=1,<2'`, etc.). `None` for actions
 * that don't move a package version (RefreshSync, RescanStale,
 * WhitelistTyposquat).
 */
recommended_version: string | null, 
/**
 * RFC 3339 timestamp — `Some` when the action was dismissed but
 * `collect_all` decided to surface it anyway (currently we filter
 * them out so this stays `None` in the default read path; kept in
 * the DTO so Phase 12b can render a "recently dismissed" tab later
 * without a schema change).
 */
dismissed_at: string | null, 
/**
 * RFC 3339 deadline after which a deferred action resurfaces. Same
 * caveat as `dismissed_at` — filtered upstream today, but exposed
 * on the DTO for forward compatibility.
 */
deferred_until: string | null, };
