// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query string for `GET /api/actions`. `min_severity` accepts the same
 * lexicon as the rest of the dashboard (`critical` / `high` / `medium`
 * / `low` / `info`); unknown values are ignored (no 400 — keeps the
 * URL forgiving when the CLI and dashboard drift).
 */
export type ActionsQuery = { project: string | null, min_severity: string | null, };
