// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";

export type ActionsResponse = { actions: Array<Action>, 
/**
 * Count *before* the `min_severity` filter — lets the dashboard
 * render "showing 3 of 12" without a second request.
 */
total: number, };
