// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Severity ladder. Declaration order matters — `derive(PartialOrd, Ord)`
 * uses it, so filters like `actions.retain(|a| a.severity >= threshold)`
 * and the sort in `collect_all` depend on `Malware > Critical > High >
 * Medium > Low > Info`.
 */
export type ActionSeverity = "Info" | "Low" | "Medium" | "High" | "Critical" | "Malware";
