// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActionDeferResponse = { 
/**
 * RFC 3339 deadline; the action resurfaces once `now >= deferred_until`.
 */
deferred_until: string, };
