// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every kind of action the generator can emit. Ordered roughly by the
 * Phase 12a design matrix — callers sort by `ActionSeverity` first, then
 * use `ActionKind` only for display grouping.
 */
export type ActionKind = "FixMalware" | "FixCveCritical" | "FixCveHigh" | "ClearViolation" | "ResolveInsufficient" | "WhitelistTyposquat" | "RefreshSync" | "RescanStale";
