// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /api/projects` body. The `path` field is taken at face value
 * (no env-var expansion); validation happens in the handler.
 */
export type AddProjectRequest = { path: string, };
