// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CompatDependent = { ecosystem: string, name: string, version: string, range: string, kind: string, 
/**
 * Phase 7b: repo path the dependent was observed in. Canonicalized
 * exactly like `WorkspaceInfo.path` so the UI can group the "Used
 * by" list per workspace and cross-reference the header selector.
 */
workspace: string, };
