// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompatDependent } from "./CompatDependent";
import type { CompatRow } from "./CompatRow";

export type CompatResponse = { ecosystem: string, name: string, installed: string | null, 
/**
 * One row per known version, ordered oldest → newest. Engines is a
 * `{ runtime → required_range }` map (e.g. `{"node": ">=14"}`).
 */
rows: Array<CompatRow>, 
/**
 * Direct dependents within the scanned repos — count + sample list,
 * so the UI can show "used by 12 packages" + a preview.
 */
dependents: Array<CompatDependent>, };
