// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompatPeerDep } from "./CompatPeerDep";

export type CompatRow = { version: string, engines: { [key in string]?: string }, peer_deps: { [key in string]?: CompatPeerDep }, };
