// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContaminatedQuery = { 
/**
 * Advisory id to trace back (GHSA-/CVE-/MAL-…). Matching is by
 * `cve_id` first, then by `source:advisory_id`.
 */
vuln_id: string, 
/**
 * Phase 7: scope the BFS to a single workspace. `None` = aggregate
 * across every scanned repo.
 */
project: string | null, };
