// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContaminationChain } from "./ContaminationChain";
import type { ContaminationHit } from "./ContaminationHit";

export type ContaminationResult = { 
/**
 * Every `(package, version)` the advisory hits directly, so the UI
 * can highlight them as the "patient zero" set.
 */
hits: Array<ContaminationHit>, 
/**
 * Sorted, deduplicated chains: each chain starts at a direct dep and
 * ends at one of the hits. Capped server-side (see
 * `services::graph::MAX_CHAINS`).
 */
chains: Array<ContaminationChain>, 
/**
 * `true` when the BFS was answered from the cache.
 */
from_cache: boolean, };
