// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContaminationChain = { 
/**
 * Ordered root-first list of `ecosystem:name@version` node ids.
 */
path: Array<string>, workspace: string, };
