// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FsEntry } from "./FsEntry";

/**
 * Wire shape for `GET /api/fs/browse?path=<absolute>`. Sandboxed to
 * `$HOME`: requests for paths whose canonical form lies outside `$HOME`
 * are rejected with HTTP 403. Only directories are listed — file
 * content is irrelevant for a directory picker.
 */
export type FsBrowseResponse = { 
/**
 * Canonical absolute path of the directory listed.
 */
path: string, 
/**
 * Canonical absolute path of the parent directory. `None` when
 * `path == $HOME` so the picker can hide the up-one-level button
 * at the sandbox boundary.
 */
parent: string | null, entries: Array<FsEntry>, 
/**
 * `true` when the response was capped at the per-directory limit
 * (default 500). The frontend should surface a "refine your
 * search" hint when this is set.
 */
truncated: boolean, };
