// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FsEntry = { 
/**
 * Entry name only (no path separators). Hidden entries (leading
 * `.`) are filtered out before serialization, except that `.git/`
 * surfaces via the parent's `has_git` flag — never as an entry.
 */
name: string, 
/**
 * Absolute canonical path of the entry.
 */
path: string, 
/**
 * `true` when the entry contains a `.git/` subdirectory directly.
 */
has_git: boolean, 
/**
 * `true` when the entry contains at least one supported manifest
 * directly (`package.json`, `pyproject.toml`, `poetry.lock`,
 * `uv.lock`, `pnpm-lock.yaml`, `yarn.lock`, `package-lock.json`,
 * or any `requirements*.txt`).
 */
has_manifest: boolean, };
