// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FsRootEntry = { 
/**
 * Display label, e.g. `"$HOME"` or `"$HOME/Repo"`.
 */
label: string, 
/**
 * Absolute canonical path on disk.
 */
path: string, };
