// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FsRootEntry } from "./FsRootEntry";

/**
 * Wire shape for `GET /api/fs/roots`. Returns conventional starting
 * points for the AddProjectModal directory picker. `entries[0]` is
 * always `$HOME`; the remainder are conventional repo dirs that exist
 * on disk (`Repo`, `Projects`, `Code`, `Workspace`, `Documents`, `src`).
 */
export type FsRootsResponse = { 
/**
 * Canonical absolute path of the user's home directory.
 */
home: string, entries: Array<FsRootEntry>, };
