// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphQuery = { 
/**
 * Optional manifest path for a specific workspace (as listed in the
 * store); when `None` the graph spans every workspace of the configured
 * repo. The string matches the stored `workspaces.manifest_path`.
 */
workspace: string | null, 
/**
 * Cap on BFS depth from direct deps. `None` = no cap. Clamped to
 * `[0, 64]` server-side so a pathological client can't blow out
 * memory on a cyclic graph.
 */
max_depth: number | null, 
/**
 * Comma-separated subset of `runtime,dev,peer,optional`. `None` =
 * include everything.
 */
kind: string | null, };
