// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphEdge } from "./GraphEdge";
import type { GraphNode } from "./GraphNode";

export type GraphResponse = { nodes: Array<GraphNode>, edges: Array<GraphEdge>, 
/**
 * Emitted when the node count exceeds the Cytoscape-native sweet
 * spot (~2000). The dashboard shows the warning and prompts the user
 * to tighten filters.
 */
oversize_warning: string | null, };
