// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComplianceTag } from "./ComplianceTag";

export type GraphNode = { 
/**
 * `ecosystem:name@version` — unique id across ecosystems. Also the
 * anchor the detail page links use.
 */
id: string, ecosystem: string, name: string, version: string, 
/**
 * `true` when this node is a direct dep of at least one workspace,
 * so the UI can tint roots differently.
 */
is_root: boolean, 
/**
 * Highest CVE severity hitting this version, `None` when clean.
 */
cve_severity: string | null, has_malware: boolean, has_typosquat: boolean, compliance: ComplianceTag | null, };
