// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphEdge = { source: string, target: string, 
/**
 * Declared range from the source side (what the parent asked for).
 */
range: string, 
/**
 * "runtime" | "dev" | "peer" | "optional".
 */
kind: string, 
/**
 * `true` when the target didn't resolve — peer deps can legitimately
 * stay unresolved; the UI renders them as a dashed halo.
 */
unresolved: boolean, };
