// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphQuery = { 
/**
 * Phase 7: scope to a single repo (path returned by
 * `/api/workspaces`). `None` = aggregate across every scanned repo.
 */
project: string | null, 
/**
 * Optional manifest path to narrow within the chosen repo. The
 * string matches the stored `workspaces.manifest_path`. Only
 * meaningful when `project` is also provided.
 */
workspace: string | null, 
/**
 * Cap on BFS depth from direct deps. `None` = no cap. Clamped to
 * `[0, 64]` server-side so a pathological client can't blow out
 * memory on a cyclic graph.
 */
max_depth: number | null, 
/**
 * Comma-separated subset of `runtime,dev,peer,optional`. `None` =
 * include everything.
 */
kind: string | null, };
