// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComplianceTag } from "./ComplianceTag";
import type { PackageRisk } from "./PackageRisk";
import type { VersionRow } from "./VersionRow";

export type PackageDetail = { ecosystem: string, name: string, installed: string | null, latest: string | null, last_scanned_at: string | null, compliance: ComplianceTag, risk: PackageRisk, versions: Array<VersionRow>, };
