// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComplianceTag } from "./ComplianceTag";
import type { MalwareEntry } from "./MalwareEntry";
import type { PackageRisk } from "./PackageRisk";
import type { PolicyProvenanceEntry } from "./PolicyProvenanceEntry";
import type { PolicySourceDto } from "./PolicySourceDto";
import type { PolicyTrace } from "./PolicyTrace";
import type { VersionRow } from "./VersionRow";
import type { VulnerabilityEntry } from "./VulnerabilityEntry";

export type PackageDetail = { ecosystem: string, name: string, installed: string | null, latest: string | null, last_scanned_at: string | null, compliance: ComplianceTag, risk: PackageRisk, versions: Array<VersionRow>, 
/**
 * Every advisory that matches *any* known version of this package — the
 * `affects_installed` flag marks the subset that drives the compliance
 * tag. The timeline uses the full list to colour individual markers.
 */
vulnerabilities: Array<VulnerabilityEntry>, 
/**
 * Malware + typosquat intel. Empty when the package is clean.
 */
malware: Array<MalwareEntry>, 
/**
 * Resolved policy + why the installed version is (not) compliant.
 */
policy_trace: PolicyTrace, 
/**
 * Phase 10c — the cascade chain that produced the effective policy,
 * in merge order (lowest priority first). Empty when the endpoint
 * is called without a `project` query param (scope-less access
 * falls back to built-in defaults).
 */
policy_sources: Array<PolicySourceDto>, 
/**
 * Phase 10c — per-key provenance map. Keys are dot-notation like
 * `defaults.offset.major`; values point at the source in
 * `policy_sources` that last set them. Empty alongside
 * `policy_sources` when no `project` scope is passed.
 */
policy_provenance: Array<PolicyProvenanceEntry>, };
