// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComplianceTag } from "./ComplianceTag";
import type { MalwareEntry } from "./MalwareEntry";
import type { PackageRisk } from "./PackageRisk";
import type { PolicyTrace } from "./PolicyTrace";
import type { VersionRow } from "./VersionRow";
import type { VulnerabilityEntry } from "./VulnerabilityEntry";

export type PackageDetail = { ecosystem: string, name: string, installed: string | null, latest: string | null, last_scanned_at: string | null, compliance: ComplianceTag, risk: PackageRisk, versions: Array<VersionRow>, 
/**
 * Every advisory that matches *any* known version of this package — the
 * `affects_installed` flag marks the subset that drives the compliance
 * tag. The timeline uses the full list to colour individual markers.
 */
vulnerabilities: Array<VulnerabilityEntry>, 
/**
 * Malware + typosquat intel. Empty when the package is clean.
 */
malware: Array<MalwareEntry>, 
/**
 * Resolved policy + why the installed version is (not) compliant.
 */
policy_trace: PolicyTrace, };
