// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PackagesQuery = { ecosystem: string | null, status: string | null, min_severity: string | null, has_malware: boolean | null, has_typosquat: boolean | null, q: string | null, sort: string | null, dir: string | null, page: number | null, per_page: number | null, 
/**
 * Phase 7: scope the listing to a single workspace's dependencies
 * (direct + transitive). Must match one of the paths returned by
 * `/api/workspaces`. `None` returns the aggregate across every
 * scanned repo.
 */
project: string | null, };
