// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComplianceTag } from "./ComplianceTag";

export type PolicyDryRunChange = { ecosystem: string, name: string, from: ComplianceTag, to: ComplianceTag, };
