// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PolicyOffset } from "./PolicyOffset";

export type PolicyTrace = { 
/**
 * Three-axis offset the resolver used for this package. Displayed in
 * the dashboard "Policy eval" tab.
 */
offset: PolicyOffset, pin: string | null, 
/**
 * "stable" | "pre" | "any".
 */
stability: string, min_age_days: number, 
/**
 * The version the resolver would recommend upgrading to, given the
 * active policy + the known vuln/malware data. `None` when no candidate
 * survives every filter.
 */
recommended: string | null, 
/**
 * Human-readable one-liner — same wording as the CLI report uses.
 */
reason: string, 
/**
 * Phase 9b — per-axis cascade: one line per step the resolver took
 * ("offset.major=0 (target major=19) → offset.minor=-1 (target
 * minor=1) → picked 19.1.0"). Empty when `pin` short-circuits.
 */
cascade: Array<string>, };
