// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PolicyTrace = { 
/**
 * Offset in majors below latest (0 = latest allowed).
 */
offset: number, pin: string | null, 
/**
 * "stable" | "pre" | "any".
 */
stability: string, min_age_days: number, 
/**
 * The version the resolver would recommend upgrading to, given the
 * active policy + the known vuln/malware data. `None` when no candidate
 * survives every filter.
 */
recommended: string | null, 
/**
 * Human-readable one-liner — same wording as the CLI report uses.
 */
reason: string, };
