// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PolicySourceDto = { 
/**
 * "built_in" | "user_wide" | "file" | "extends".
 */
kind: string, 
/**
 * User-facing label: "built-in default", "~/.packguard.yml", or
 * the absolute file path.
 */
label: string, 
/**
 * Absolute path when the source is a file; `None` for built-in.
 */
path: string | null, };
