// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PolicyProvenanceEntry = { 
/**
 * Dot-notation key (`defaults.offset.major`, …).
 */
key: string, 
/**
 * Index into `policy_sources`.
 */
source_index: number, 
/**
 * Best-effort 1-based YAML line; `None` when not resolvable.
 */
line: number | null, };
