// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComplianceSummary } from "./ComplianceSummary";
import type { PolicyDryRunChange } from "./PolicyDryRunChange";

export type PolicyDryRunResult = { 
/**
 * Per-bucket totals when the candidate policy is applied to the last
 * scan.
 */
candidate: ComplianceSummary, 
/**
 * Same counts under the currently active policy — lets the UI show a
 * side-by-side delta.
 */
current: ComplianceSummary, 
/**
 * Packages whose compliance tag flipped between the two policies.
 * Bounded to the first `max` entries the service decides to return
 * (currently 50) so a pathological diff doesn't explode the payload.
 */
changed_packages: Array<PolicyDryRunChange>, };
