// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Three-axis offset, mirrors `packguard_policy::Offset`. Each axis is
 * a non-negative distance below the latest `{major,minor,patch}` — so
 * `-1` in YAML surfaces here as `1`. All zero means "always latest".
 */
export type PolicyOffset = { major: number, minor: number, patch: number, };
