// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PolicyOffset } from "./PolicyOffset";

export type PolicyTrace = { 
/**
 * Three-axis offset the resolver used for this package. Displayed in
 * the dashboard "Policy eval" tab.
 */
offset: PolicyOffset, pin: string | null, 
/**
 * "stable" | "pre" | "any".
 */
stability: string, min_age_days: number, 
/**
 * The version the resolver would recommend upgrading to, given the
 * active policy + the known vuln/malware data. `None` when no candidate
 * survives every filter.
 */
recommended: string | null, 
/**
 * Human-readable one-liner — same wording as the CLI report uses.
 */
reason: string, 
/**
 * Phase 10a — lex-bound trace: one line per axis describing its
 * contribution to the effective inclusive upper bound, plus lines
 * for the merged bound and the picked remediation. Example:
 * `offset.major=-1 → (18, ∞, ∞)` / `offset.minor=0 → inactive` /
 * `effective bound = (18, ∞, ∞)` / `max version ≤ bound = 18.3.1`.
 * Empty when `pin` short-circuits.
 */
cascade: Array<string>, };
