// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PolicyDocument = { 
/**
 * Raw `.packguard.yml` contents (or the conservative defaults when no
 * file is present).
 */
yaml: string, 
/**
 * `true` when the YAML lives on disk; `false` when we're returning the
 * embedded conservative defaults.
 */
from_file: boolean, };
