// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Simple `?project=<path>` query for endpoints that only need the scope
 * filter (overview, policy get, compat).
 */
export type ProjectQuery = { project: string | null, };
