// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase 14.1f — wire shape returned by `GET /api/projects` and the
 * `succeeded` payload of an `AddProject` job. Mirrors
 * [`packguard_store::projects_registry::Project`] but flattens
 * `created_at` / `last_scan` to RFC 3339 strings so the dashboard
 * doesn't have to learn about chrono.
 */
export type ProjectDto = { id: bigint, 
/**
 * Filesystem-safe identifier derived from the canonical project
 * root path (see `packguard_core::slugify`). Stable across
 * restarts and the only handle the dashboard needs to scope
 * requests in 14.3+.
 */
slug: string, 
/**
 * Canonical absolute path of the project root (the directory that
 * contains the `.git/` ancestor). Surfaced for the UI's tooltip
 * only — internally always identify projects by `slug`.
 */
path: string, 
/**
 * Human-friendly label, defaults to the project root's
 * `file_name()`.
 */
name: string, created_at: string, last_scan: string | null, };
