// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RiskRow = { ecosystem: string, name: string, installed: string | null, 
/**
 * Weighted: critical=10, high=5, medium=2, low=1, malware=20, typosquat=1.
 */
score: number, reason: string, };
