// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncReport = { osv_npm_persisted: number, osv_pypi_persisted: number, ghsa_persisted: number, typosquat_suspects: number, };
