// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VersionRow = { version: string, published_at: string | null, deprecated: boolean, yanked: boolean, };
