// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VersionRow = { version: string, published_at: string | null, deprecated: boolean, yanked: boolean, 
/**
 * Highest severity of advisories matching this version; `None` when the
 * version is clean. Drives the marker colour on the timeline.
 */
severity: string | null, };
