// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row for the workspace selector in the dashboard header and for the
 * `packguard scans` CLI output that drives the "Available scans" error
 * hints. Sourced from `packguard_store::ScanIndexRow` (already sorted by
 * `last_scan_at DESC`); path strings are the canonicalized forms
 * persisted since Polish-1.
 */
export type WorkspaceInfo = { path: string, ecosystem: string, last_scan_at: string, fingerprint: string, dependency_count: number, };
