// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type YamlErrorLocation = { 
/**
 * 1-based line. `None` when the YAML parser couldn't recover a location
 * (rare — mostly happens for pure I/O failures).
 */
line: number | null, column: number | null, };
