// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mirror of `packguard_policy::Compliance` flattened to a string tag — the
 * frontend only needs the kind, not the full payload.
 */
export type ComplianceTag = "compliant" | "warning" | "violation" | "cve-violation" | "malware" | "typosquat" | "insufficient";
