// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PackagesQuery = { ecosystem: string | null, status: string | null, min_severity: string | null, has_malware: boolean | null, has_typosquat: boolean | null, q: string | null, sort: string | null, dir: string | null, page: number | null, per_page: number | null, };
