// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PackageRisk = { critical: number, high: number, medium: number, low: number, malware_confirmed: number, typosquat_suspects: number, };
