// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComplianceTag } from "./ComplianceTag";
import type { PackageRisk } from "./PackageRisk";

export type PackageRow = { ecosystem: string, name: string, installed: string | null, latest: string | null, kind: string, compliance: ComplianceTag, risk: PackageRisk, last_scanned_at: string | null, };
