// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageRow } from "./PackageRow";

export type PackagesPage = { total: number, page: number, per_page: number, rows: Array<PackageRow>, };
