// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScanReport = { projects_scanned: number, packages_persisted: number, registry_errors: number, };
