// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobKind } from "./JobKind";
import type { JobStatus } from "./JobStatus";
import type { JsonValue } from "./serde_json/JsonValue";

export type JobView = { id: string, kind: JobKind, status: JobStatus, started_at: string, finished_at: string | null, result: JsonValue | null, error: string | null, };
