// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComplianceSummary } from "./ComplianceSummary";
import type { EcoCount } from "./EcoCount";
import type { MalwareSummary } from "./MalwareSummary";
import type { RiskRow } from "./RiskRow";
import type { VulnSummary } from "./VulnSummary";

export type Overview = { 
/**
 * 0..=100, computed as `compliant / total * 100` (no scan → null).
 */
health_score: number | null, last_scan_at: string | null, last_sync_at: string | null, packages_total: number, packages_by_ecosystem: Array<EcoCount>, vulnerabilities: VulnSummary, malware: MalwareSummary, compliance: ComplianceSummary, top_risks: Array<RiskRow>, };
