# typed: false
# frozen_string_literal: true

# Homebrew formula for PackGuard.
#
# Auto-generated by the release workflow on each `v*` tag.
# Upstream source and template:
#   https://github.com/Tmauc/packguard/blob/main/packaging/homebrew/packguard.rb
# Bug reports for the formula itself:
#   https://github.com/Tmauc/homebrew-packguard/issues

class Packguard < Formula
  desc "Dependency supply-chain scanner: OSV/GHSA + malware/typosquat + policy-driven CI gate"
  homepage "https://github.com/Tmauc/packguard"
  version "RELEASE_VERSION_PLACEHOLDER"
  license "MIT OR Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/Tmauc/packguard/releases/download/v#{version}/packguard-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "RELEASE_SHA256_DARWIN_ARM64_PLACEHOLDER"
    end
    on_intel do
      url "https://github.com/Tmauc/packguard/releases/download/v#{version}/packguard-v#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "RELEASE_SHA256_DARWIN_X64_PLACEHOLDER"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Tmauc/packguard/releases/download/v#{version}/packguard-v#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "RELEASE_SHA256_LINUX_ARM64_PLACEHOLDER"
    end
    on_intel do
      url "https://github.com/Tmauc/packguard/releases/download/v#{version}/packguard-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "RELEASE_SHA256_LINUX_X64_PLACEHOLDER"
    end
  end

  def install
    bin.install "packguard"
    # Carry the README + license into Cellar so `brew info packguard`
    # renders the homepage correctly and license audits see a licence
    # file alongside the binary.
    doc.install "README.md" if File.exist?("README.md")
    %w[LICENSE LICENSE-APACHE LICENSE-MIT].each do |f|
      pkgshare.install f if File.exist?(f)
    end
  end

  test do
    # Smoke tests: `--version` prints the tagged version, `init` writes
    # a conservative policy in the temp Testpath sandbox. These two
    # together exercise the binary's IO + its policy crate.
    assert_match version.to_s, shell_output("#{bin}/packguard --version")
    system "#{bin}/packguard", "init", testpath.to_s, "--force"
    assert_predicate testpath/".packguard.yml", :exist?
  end
end
